### ISSUE TITLE
conda bug prevents installing anything that depends on petsc

### ISSUE THREAD

**Issue by tlunet** [conda-forge/petsc-feedstock#147]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi, 

a weird issue occurs on my side when updating conda environment today :

```
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/prog/anaconda/lib/python3.8/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
        return getattr(module, func_name)(args, parser)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/prog/anaconda/lib/python3.8/site-packages/conda/cli/install.py", line 259, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/solve.py", line 1058, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/index.py", line 290, in get_reduced_index
        push_record(record)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/core/index.py", line 264, in push_record
        combined_depends = record.combined_depends
      File "/prog/anaconda/lib/python3.8/site-packages/conda/models/records.py", line 340, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/prog/anaconda/lib/python3.8/site-packages/conda/models/match_spec.py", line 476, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/prog/anaconda/lib/python3.8/site-packages/conda/models/match_spec.py", line 476, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/prog/anaconda/lib/python3.8/site-packages/conda/models/match_spec.py", line 506, in _merge
        final = this_component.merge(that_component)
      File "/prog/anaconda/lib/python3.8/site-packages/conda/models/match_spec.py", line 757, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - '*complex*'
      - 'complex_*'
```

After searching a bit, it appears to arise when anaconda is comparing version specifications, and find incompatibility between two build of petsc, namely :

```
petsc=[build=*complex*]
petsc[version='>=3.17.3,<3.18.0a0',build=complex_*]
```

And because `*complex*` is not equal to `complex_*`, conda crashes :sweat_smile:

After looking a bit at the recent changes, I noticed the change at line 27 in https://github.com/conda-forge/petsc-feedstock/commit/7c2b2116afd881ff2608ea31b405548266b09767 that may have something to do with it (but I'm not so sure at all, it's just a first hypothesis).

Finally, I could avoid the crash (and perform an update) by forcing conda to merge the two specifications when identifying petsc (hard coded in conda code), but I'm not sure this is a valid and safe way to solve it ...

PS : depending on the conda update (if only one package, ...), the exception can also be :

```
ValueError: Incompatible component merge:
      - '*real*'
      - 'real_*'
```

### Installed packages

```shell
# packages in environment at /prog/anaconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   0.13.0                   pypi_0    pypi
alabaster                 0.7.12                     py_0    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
anyio                     3.6.1            py38h578d9bd_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h0a891b7_2    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
asgiref                   3.5.2              pyhd8ed1ab_0    conda-forge
astroid                   2.6.6                    pypi_0    pypi
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attr                      2.5.1                h166bdaf_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.6.0             pyhd8ed1ab_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotli-python             1.0.9            py38hfa26641_7    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15        py38h578d9bd_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_0    conda-forge
chardet                   5.0.0            py38h578d9bd_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py38h578d9bd_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
cma                       3.1.0                    pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1                   pypi_0    pypi
conda                     4.13.0           py38h578d9bd_1    conda-forge
conda-build               3.21.9           py38h578d9bd_1    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-package-handling    1.8.1            py38h0a891b7_1    conda-forge
conda-verify              3.1.1           py38h578d9bd_1004    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
coverage                  6.4.1            py38h0a891b7_0    conda-forge
cryptography              37.0.2           py38h2b5fc30_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dash                      2.5.1              pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.0            py38hfa26641_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
docutils                  0.18.1           py38h578d9bd_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
fastapi                   0.78.0             pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          mpi_openmpi_h36312d9_2    conda-forge
filelock                  3.7.1              pyhd8ed1ab_0    conda-forge
flake8                    4.0.1              pyhd8ed1ab_2    conda-forge
flake8-bugbear            22.7.1             pyhd8ed1ab_0    conda-forge
flake8-comprehensions     3.10.0             pyhd8ed1ab_0    conda-forge
flask                     2.1.2              pyhd8ed1ab_1    conda-forge
flask-compress            1.12               pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.33.3           py38h0a891b7_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py38h578d9bd_5    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.70.2               h780b84a_4    conda-forge
glib-tools                2.70.2               h780b84a_4    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2            py38h8384b0a_0    conda-forge
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.20.3               hd4edc92_0    conda-forge
h11                       0.13.0             pyhd8ed1ab_1    conda-forge
hdf5                      1.12.1          mpi_openmpi_hb3f3608_4    conda-forge
humanfriendly             10.0                     pypi_0    pypi
hypre                     2.25.0          mpi_openmpi_ha709252_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py38h578d9bd_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.15.0             pyh210e3f2_0    conda-forge
ipython                   7.33.0           py38h578d9bd_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jack                      1.9.18            h8c3723f_1002    conda-forge
jedi                      0.18.1           py38h578d9bd_1    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jellyfish                 0.9.0            py38h0a891b7_1    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
jsonschema                4.6.1              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0           py38h578d9bd_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
keyring                   23.6.0           py38h578d9bd_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.3            py38h43d8883_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lazy-object-proxy         1.7.1            py38h0a891b7_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.5.2                hb890918_3    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcap                    2.64                 ha37c62d_0    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libclang                  14.0.6          default_h2e3cab8_0    conda-forge
libclang13                14.0.6          default_h3a83d3e_0    conda-forge
libcups                   2.3.3                hf5a7f15_1    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.12                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
liblief                   0.11.5               h9c3ff4c_1    conda-forge
libllvm11                 11.1.0               hf817b99_3    conda-forge
libllvm14                 14.0.6               he0ac6c6_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.4                 hd77ab85_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                hc85c160_1    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libudev1                  249                  h166bdaf_4    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.14               h22db469_2    conda-forge
libzlib                   1.2.12               h166bdaf_1    conda-forge
llvmlite                  0.38.1           py38h38d86a4_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markdown                  3.3.7              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38h0a891b7_1    conda-forge
matplotlib                3.5.2            py38h578d9bd_0    conda-forge
matplotlib-base           3.5.2            py38h826bfd8_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mistune                   0.8.4           py38h497a2fe_1005    conda-forge
mpc                       1.2.1                h9f54685_0    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.1.1                    pypi_0    pypi
mpi4py-fft                2.0.4            py38h6d9dd19_2    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
multidict                 6.0.2                    pypi_0    pypi
mumps-include             5.2.1               ha770c72_11    conda-forge
mumps-mpi                 5.2.1               hfb3545b_11    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py38h578d9bd_5    conda-forge
mysql-common              8.0.29               haf5c9bc_1    conda-forge
mysql-libs                8.0.29               h28c427c_1    conda-forge
nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numba                     0.55.2           py38hdc3674a_0    conda-forge
numpy                     1.22.4           py38h99721a1_0    conda-forge
numpydoc                  1.4.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openmpi                   4.1.4              ha1ae619_100    conda-forge
openssl                   1.1.1p               h166bdaf_0    conda-forge
ortools                   9.0.9048                 pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py38h47df419_0    conda-forge
pandoc                    2.18                 ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parmetis                  4.0.3             he9a3056_1005    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.14.5               h58526e2_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
petsc                     3.17.3          real_h1c6c8d6_100    conda-forge
petsc4py                  3.17.2          real_h9dce1aa_100    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.1            py38h0ee0e06_1    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
plotly                    5.9.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38h578d9bd_3    conda-forge
portaudio                 19.6.0               h57a0ea0_5    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
protobuf                  3.17.3                   pypi_0    pypi
psutil                    5.9.1            py38h0a891b7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptscotch                  6.0.9                h0a9c416_2    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio                14.0                 h7f54b18_8    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-lief                   0.11.5           py38h709712a_1    conda-forge
pybind11                  2.9.2            py38h43d8883_1    conda-forge
pybind11-global           2.9.2            py38h43d8883_1    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py38h0a891b7_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.9.1            py38h0a891b7_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pylint                    2.9.6                    pypi_0    pypi
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.4           py38h7492b6b_1    conda-forge
pyqt5-sip                 12.9.0           py38hfa26641_1    conda-forge
pyqtwebengine             5.15.4           py38h7492b6b_1    conda-forge
pyrsistent                0.18.1           py38h0a891b7_1    conda-forge
pysocks                   1.7.1            py38h578d9bd_5    conda-forge
pytest                    7.1.2            py38h578d9bd_0    conda-forge
pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
python                    3.8.13          h582c2e5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python-levenshtein        0.12.2           py38h0a891b7_2    conda-forge
python-libarchive-c       4.0              py38h578d9bd_1    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.4.1              pyhd8ed1ab_1    conda-forge
python-slugify            6.1.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytoolconfig              1.2.1              pyhd8ed1ab_0    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyxdg                     0.28               pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h0a891b7_4    conda-forge
pyzmq                     23.2.0           py38hfc09fa9_0    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.4               ha5833f6_2    conda-forge
qt-webengine              5.15.4               hcbadb6c_3    conda-forge
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.3.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.1              pyha770c72_0    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
rope                      1.2.0              pyhd8ed1ab_0    conda-forge
rtree                     1.0.0            py38h02d302b_1    conda-forge
ruamel_yaml               0.15.80         py38h0a891b7_1007    conda-forge
scalapack                 2.2.0                h67de57e_1    conda-forge
scipy                     1.8.1            py38h1ee437e_0    conda-forge
scotch                    6.0.9                hb2e6521_2    conda-forge
secretstorage             3.3.2            py38h578d9bd_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                63.1.0           py38h578d9bd_0    conda-forge
shapely                   1.7.1                    pypi_0    pypi
sip                       6.5.1            py38h709712a_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py38h578d9bd_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sphinx                    5.0.2              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.3.1            py38h578d9bd_0    conda-forge
spyder-kernels            2.3.1            py38h578d9bd_0    conda-forge
spyder-notebook           0.1.4                      py_0    spyder-ide
sqlite                    3.39.0               h4ff8645_0    conda-forge
starlette                 0.19.1             pyhd8ed1ab_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
superlu                   5.2.2                h00795ac_0    conda-forge
superlu_dist              7.2.0                h34f6f4d_0    conda-forge
sympy                     1.10.1           py38h578d9bd_0    conda-forge
tabulate                  0.8.10             pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.15.0           py38h578d9bd_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.3.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.0             pyha770c72_0    conda-forge
torcpy                    0.1.1                    pypi_0    pypi
tornado                   6.2              py38h0a891b7_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.4            py38h0a891b7_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
ujson                     5.3.0            py38hfa26641_0    conda-forge
unicodedata2              14.0.0           py38h0a891b7_1    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
uvicorn                   0.17.6           py38h578d9bd_1    conda-forge
watchdog                  2.1.9            py38h578d9bd_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1           py38h0a891b7_0    conda-forge
wurlitzer                 3.0.2              pyhd8ed1ab_2    conda-forge
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
yarl                      1.4.2                    pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.5.2                h8a70e8d_2    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /prog/anaconda
            shell level : 1
       user config file : /home/cpf5546/.condarc
 populated config files : /home/cpf5546/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.8.13.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.3.18=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /prog/anaconda  (writable)
      conda av data dir : /prog/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/default/linux-64
                          https://conda.anaconda.org/default/noarch
          package cache : /prog/anaconda/pkgs
                          /home/cpf5546/.conda/pkgs
       envs directories : /prog/anaconda/envs
                          /home/cpf5546/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.8.13 Linux/5.3.18-150300.59.71-default opensuse-leap/15.3 glibc/2.31
                UID:GID : 2024:2000
             netrc file : None
           offline mode : False
```

**Comment by dalcinl** [comment]
@minrk We need your input here.

**Comment by minrk** [comment]
Arg, this is certainly a conda solver bug that it can't merge overlapping globs (https://github.com/conda/conda/issues/11442). The only solution in the meantime is to be consistent with pinning.

The above 3 PRs rely on the new run_exports to ensure consistent pinning.

**Comment by minrk** [comment]
repodata [patch](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/295) has been applied, so this should be resolved.
